AWSTemplateFormatVersion: "2010-09-09"
Description: Creates an ec2 keypair called 'lab-key-pair'

Parameters:
  KeyPairName:
    Description: Name used for the key pair to be generated.
    Type: String
    Default: lab-key-pair

Resources:

  CreateKeyPairLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        -
          PolicyName: lambdaKeyPairPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "logs:*"
                  - "ec2:CreateKeyPair"
                  - "ec2:DeleteKeyPair"
                  - "ec2:DescribeKeyPairs"
                Resource: "*"


  CreateKeyPairLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
        Code:
          ZipFile: |
                  import cfnresponse
                  import json
                  import boto3
                  def lambda_handler(event, context):
                    print(f"Data in event: {event}")
                    response_data = {}
                    keyPairName = event["ResourceProperties"]["KeyPairName"]
                    ec2 = boto3.client('ec2')
                    if event["RequestType"] == "Create":
                      try:
                        ec2.describe_key_pairs(KeyNames=[keyPairName,],)
                      except Exception as e:
                        response = ec2.create_key_pair(KeyName=keyPairName)
                    elif event["RequestType"] == "Delete":
                      response = ec2.delete_key_pair(KeyName=keyPairName)
                    cfnresponse.send(event, context, cfnresponse.SUCCESS, response_data)
        Handler: index.lambda_handler
        Runtime: python3.9
        Role: !GetAtt CreateKeyPairLambdaExecutionRole.Arn
        MemorySize: 128
        Timeout: 10

  KeyPair:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      KeyPairName: !Ref KeyPairName
      ServiceToken: !GetAtt CreateKeyPairLambdaFunction.Arn

Outputs:
  KeyPairName:
    Value: !Ref KeyPairName
    Description: KeyPair to use when needed