AWSTemplateFormatVersion: 2010-09-09
Description: Main template with parameters

Mappings:
  RegionMap:
    ap-northeast-1:
      AZs: 'ap-northeast-1a,ap-northeast-1b,ap-northeast-1c'
    ap-northeast-2:
      AZs: 'ap-northeast-2a,ap-northeast-2b,ap-northeast-2c'
    ap-northeast-3:
      AZs: 'ap-northeast-3a,ap-northeast-3b,ap-northeast-3c'
    us-east-2:
      AZs: 'us-east-2a,us-east-2b,us-east-2c'
    us-east-1:
      AZs: 'us-east-1a,us-east-1b,us-east-1c,us-east-1d'
    us-west-1:
      AZs: 'us-west-1a,us-west-1b'
    us-west-2:
      AZs: 'us-west-2a,us-west-2b,us-west-2c'
    ap-south-1:
      AZs: 'ap-south-1a,ap-south-1b,ap-south-1c'
    ap-southeast-1:
      AZs: 'ap-southeast-1a,ap-southeast-1b,ap-southeast-1c'
    ap-southeast-2:
      AZs: 'ap-southeast-2a,ap-southeast-2b,ap-southeast-2c'
    ca-central-1:
      AZs: 'ca-central-1a,ca-central-1b,ca-central-1d'
    eu-central-1:
      AZs: 'eu-central-1a,eu-central-1b,eu-central-1c'
    eu-west-1:
      AZs: 'eu-west-1a,eu-west-1b,eu-west-1c'
    eu-west-2:
      AZs: 'eu-west-2a,eu-west-2b,eu-west-2c'
    eu-west-3:
      AZs: 'eu-west-3a,eu-west-3b,eu-west-3c'
    eu-north-1:
      AZs: 'eu-north-1a,eu-north-1b,eu-north-1c'
    sa-east-1:
      AZs: 'sa-east-1a,sa-east-1b,sa-east-1c'
    # ap-east-1:
    #   AZs: 'ap-east-1a,ap-east-1b,ap-east-1c'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Demo Environment Setup
        Parameters:
          - BuildEcs
    ParameterLabels:
      BuildEcs:
        default: Deploy ECS Demo Cluster
Parameters:
  BuildEcs:
    Type: String
    AllowedValues: 
      - true
      - false
    Default: true
  FargateSupport:
    Type: String
    AllowedValues: 
      - true
      - false
    Default: false
Conditions:
  BuildEcs: !Equals 
    - !Ref BuildEcs
    - true
  FargateSupport: !Equals 
    - !Ref FargateSupport
    - true
  NoFargateSupport:
      "Fn::Not":
        - Condition: FargateSupport

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !If [FargateSupport, 'https://v1-demo-environments.s3.amazonaws.com/utils/vpc.template-fargate.yaml', 'https://v1-demo-environments.s3.amazonaws.com/utils/vpc.template.yaml'] 
      Parameters:
        NumberOfAZs: 2
        AvailabilityZones: !FindInMap
          - RegionMap
          - !Ref 'AWS::Region'
          - AZs
  KeyPairStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://v1-demo-environments.s3.amazonaws.com/utils/keypair.template.yaml'

  ECSStack:
    Condition: BuildEcs
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://v1-demo-environments.s3.amazonaws.com/utils/ecs.template.yaml'
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VPCID
        KeyName: !GetAtt KeyPairStack.Outputs.KeyPairName
        SubnetId: 
          Fn::Join:
            - ','
            - - !GetAtt VPCStack.Outputs.PublicSubnet1ID
              - !GetAtt VPCStack.Outputs.PublicSubnet2ID
    DependsOn:
      - VPCStack
      - KeyPairStack

  EcsServiceStack:
    Condition: BuildEcs
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://v1-demo-environments.s3.amazonaws.com/utils/ecs-service.template.yaml'
      Parameters:
        ECSClusterName: !GetAtt ECSStack.Outputs.ecscluster
        taskdefinition: !GetAtt ECSStack.Outputs.taskdef
    DependsOn:
      - ECSStack
  
Outputs:
  PublicSubnet1ID:
    Description: Public subnet 1 ID in Availability Zone 1
    Value: !GetAtt VPCStack.Outputs.PublicSubnet1ID
  PublicSubnet2ID:
    Description: Public subnet 2 ID in Availability Zone 2
    Value: !GetAtt VPCStack.Outputs.PublicSubnet2ID
