AWSTemplateFormatVersion : 2010-09-09
Description : Creating a random string custom resource
Resources:

 LambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
            - sts:AssumeRole
        Policies:
          -
            PolicyName: allowLambdaLogging
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action:
                    - "logs:*"
                  Resource: "*"


 RandomStringLambdaFunction:
   Type: AWS::Lambda::Function
   Properties:
      Code:
        ZipFile: |
                import cfnresponse
                from random import choice
                from string import ascii_lowercase, digits, ascii_uppercase
                def random_string(length=8, chars=ascii_lowercase + digits + ascii_uppercase + "@^_*-"):
                  return "".join(choice(chars) for x in range(length))
                def lambda_handler(event, context):
                  print(f"Data in event: {event}")
                  response_data = {}
                  if event["RequestType"] == "Create":
                    string_length = int(event["ResourceProperties"]["Length"])
                    physicalResourceId = random_string(string_length) + "a^1B" 
                    response_data = { "RandomString": physicalResourceId }
                  
                  else: # if event["RequestType"] == "Update" or event["RequestType"] == "Delete":
                    physicalResourceId = event["PhysicalResourceId"]
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, response_data, physicalResourceId)
      Handler: index.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 128
      Timeout: 10

 # Custom Resource 1
 SecretPassword:
   Type: AWS::CloudFormation::CustomResource
   Properties:
     Length: "12"
     ServiceToken: !GetAtt RandomStringLambdaFunction.Arn

 # Outputs
Outputs:
 SecretPassword:
    Value: !GetAtt SecretPassword.RandomString
    Description: "Sample random string generated by lambda function using Python3.11"
