apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-goof
  namespace: demo
  labels:
    app: java-goof
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-goof
  template:
    metadata:
      labels:
        app: java-goof
    spec:
      containers:
      - name: java-goof
        image: public.ecr.aws/trendvisionone-community/java-demo
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: java-goof-service
  namespace: demo
  labels:
    app: java-goof
spec:
  selector:
    app: java-goof
  type: ClusterIP  
  ports:
  - port: 80
    targetPort: 8080