apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: demo
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: public.ecr.aws/k1q0d6m0/openssl3-demo
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: demo
  labels:
    app: web-app
spec:
  selector:
    app: web-app
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
